language: python
python:
  - "3.5"
before_install:
  - "sudo apt-get -qq update"
  - "sudo apt-get install -y liblapack-dev libatlas-base-dev gfortran g++"
install:
  - "pip install -r requirements.txt"
  - "pip install nose==1.3.7 coveralls==1.1 pylint==1.6.4"
script:
  - "pylint --disable=C,E vardaa || true" # report about warnings and refactoring.
  - "pylint -E vardaa" # detect errors. if detected, the build would be failed
  - "pylint -E tests" # detect errors for test code.
  - "nosetests --with-coverage --cover-package=vardaa" # execute unit tests.
after_success:
  - "coveralls"
